version = "2.5.6"

[package]
name = "hula"
version = "2.5.3"
description = "hula"
authors = [ "nongyehong" ]
license = ""
repository = ""
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[build-dependencies.tauri-build]
version = "2.0.2"
features = [ ]

[dependencies]
tauri-plugin-os = "2.0.1"
tauri-plugin-shell = "2.0.1"
serde_json = "1"
tauri-plugin-websocket = "2.0.1"
tauri-plugin-process = "2.0.1"
tauri-plugin-fs = "2.0.1"
tauri-plugin-dialog = "2.0.1"
tauri-plugin-upload = "2.0.1"
tauri-plugin-global-shortcut = "2.0.1"
tauri-plugin-clipboard-manager = "2.0.1"
tauri-plugin-updater = "2"
tauri-plugin-single-instance = "2"

  [dependencies.tauri]
  version = "2.0.6"
  features = [ "macos-private-api", "tray-icon", "image-png" ]

  [dependencies.serde]
  version = "1"
  features = [ "derive" ]

  [dependencies.tauri-plugin-http]
  version = "2.0.1"
  features = [ "unsafe-headers" ]

  [dependencies.tauri-plugin-sql]
  version = "2"
  features = [ "sqlite" ]

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-autostart = "2.0.1"
lazy_static = "1.4"
screenshots = "0.5.4"
base64 = "0.22.1"
rodio = "0.17.3"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
