name: '🐛 Bug Report'
description: 'Report an bug'
title: '[bug] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/HuLaSpark/HuLa-IM-Tauri/issues?q=is%3Aissue) about this problem first.
        2. Make sure `rustc` and all relevant HuLa-IM-Tauri packages are up to date.
        3. Make sure it's an issue with HuLa-IM-Tauri and not something else you are using.
        4. Remember to follow our community guidelines and be friendly.

  - type: input
    attributes:
      label: '📌 Version'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: '💻 Operating System'
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
    validations:
      required: true

  - type: textarea
    attributes:
      label: '🐛 Bug Description'
      description: A clear and concise description of the bug, Include screenshots if applicable.
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: '☄️ intact `tauri info` output'
      description: '“pnpm run tauri info” or “cargo tauri info” output'
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: '📷 Recurrence Steps'
      description: A clear and concise description of how to recurrence.

  - type: textarea
    attributes:
      label: '🚦 Expected Behavior'
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: '📝 Additional Information'
      description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.